/**
 * Backend API client.
 *
 * In dev, requests to `/api/*` are proxied to the FastAPI server by Vite
 * (see vite.config.ts). In other environments, set VITE_API_BASE_URL.
 */
import { useVoice } from "../store/voice";

const BASE_URL = import.meta.env.VITE_API_BASE_URL ?? "";
const DEFAULT_TIMEOUT = 60_000; // generous: DeepSeek replies can be slow

export interface HealthResponse {
  status: string;
  app: string;
}

/**
 * Combine the caller's abort signal with a timeout so a hung request fails
 * cleanly (surfaced as an error the UI can show) instead of spinning forever.
 */
export function withTimeout(signal: AbortSignal | undefined | null, ms: number): AbortSignal | undefined {
  if (typeof AbortSignal === "undefined" || typeof AbortSignal.timeout !== "function") {
    return signal ?? undefined;
  }
  const timeout = AbortSignal.timeout(ms);
  if (!signal) return timeout;
  const anyFn = (AbortSignal as unknown as { any?: (s: AbortSignal[]) => AbortSignal }).any;
  return anyFn ? anyFn([signal, timeout]) : signal;
}

async function request<T>(path: string, init?: RequestInit, timeoutMs = DEFAULT_TIMEOUT): Promise<T> {
  const res = await fetch(`${BASE_URL}${path}`, {
    headers: { "Content-Type": "application/json" },
    ...init,
    signal: withTimeout(init?.signal, timeoutMs),
  });
  if (!res.ok) {
    throw new Error(`${init?.method ?? "GET"} ${path} failed: ${res.status}`);
  }
  return res.json() as Promise<T>;
}

/** Liveness check used to surface backend connectivity in the UI. */
export function getHealth(signal?: AbortSignal): Promise<HealthResponse> {
  return request<HealthResponse>("/api/health", { signal });
}

export type ChatRole = "user" | "assistant";

export interface ChatMessage {
  role: ChatRole;
  content: string;
}

export interface ChatResponse {
  scenario_id: string;
  reply: string;
  opening: boolean;
}

/** A user-defined role-play scene generated by DeepSeek. */
export interface CustomScene {
  title: string;
  title_zh: string;
  partner_role: string;
  goal: string;
  persona: string;
  opening_line: string;
  /** Short Chinese theme tag (display-only), e.g. "日常生活·邻里". */
  source?: string;
}

/** Expand a learner's short description into a full role-play scene. */
export function createCustomScene(
  description: string,
  signal?: AbortSignal,
): Promise<CustomScene> {
  return request<CustomScene>("/api/custom-scenario", {
    method: "POST",
    body: JSON.stringify({ description }),
    signal,
  });
}

/** A fresh, ready-to-play scene to feature as the day's recommendation. */
export function getScenarioSuggestion(signal?: AbortSignal): Promise<CustomScene> {
  return request<CustomScene>("/api/scenario-suggestion", { signal });
}

/**
 * One role-play turn. Pass the conversation so far; an empty list asks the
 * backend for the scripted scene opener (no model call). Pass `custom` to
 * role-play a user-defined scene instead of a catalogue scenario.
 */
export function postChat(
  scenarioId: string,
  messages: ChatMessage[],
  signal?: AbortSignal,
  custom?: CustomScene,
): Promise<ChatResponse> {
  return request<ChatResponse>("/api/chat", {
    method: "POST",
    body: JSON.stringify({ scenario_id: scenarioId, messages, custom }),
    signal,
  });
}

/**
 * Stream one role-play turn as plain-text deltas. `onText` receives the full
 * accumulated reply each time more arrives. Resolves with the final text.
 * Throws on any failure so the caller can fall back to {@link postChat}.
 */
export async function streamChat(
  scenarioId: string,
  messages: ChatMessage[],
  onText: (full: string) => void,
  signal?: AbortSignal,
  custom?: CustomScene,
): Promise<string> {
  const res = await fetch(`${BASE_URL}/api/chat/stream`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ scenario_id: scenarioId, messages, custom }),
    signal: withTimeout(signal, 60_000),
  });
  if (!res.ok || !res.body) throw new Error(`chat stream failed: ${res.status}`);
  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  let full = "";
  for (;;) {
    const { done, value } = await reader.read();
    if (done) break;
    full += decoder.decode(value, { stream: true });
    if (full) onText(full);
  }
  full += decoder.decode();
  const text = full.trim();
  if (!text) throw new Error("empty stream");
  return text;
}

export interface SkillScore {
  key: string;
  label_en: string;
  label_zh: string;
  score: number;
}

export interface Correction {
  original: string;
  suggestion: string;
  note: string;
}

export interface Phrase {
  text: string;
  note: string;
}

export interface FeedbackResponse {
  scenario_id: string;
  overall: number;
  summary: string;
  scores: SkillScore[];
  corrections: Correction[];
  phrases: Phrase[];
  tip: string;
}

/** Post-session feedback on a text conversation (scores, corrections, tips). */
export function postFeedback(
  scenarioId: string,
  messages: ChatMessage[],
  signal?: AbortSignal,
  custom?: CustomScene,
): Promise<FeedbackResponse> {
  return request<FeedbackResponse>("/api/feedback", {
    method: "POST",
    body: JSON.stringify({ scenario_id: scenarioId, messages, custom }),
    signal,
  });
}

export interface SessionSummary {
  id: number;
  scenario_id: string;
  overall: number;
  created_at: string;
}

export interface SessionDetail extends SessionSummary {
  summary: string;
  tip: string;
  scores: SkillScore[];
  messages: ChatMessage[];
}

export interface SaveSessionPayload {
  scenario_id: string;
  messages: ChatMessage[];
  overall: number;
  summary: string;
  tip: string;
  scores: SkillScore[];
}

/** Persist a finished session (transcript + feedback) for history/trends. */
export function postSession(
  payload: SaveSessionPayload,
  signal?: AbortSignal,
): Promise<SessionDetail> {
  return request<SessionDetail>("/api/sessions", {
    method: "POST",
    body: JSON.stringify(payload),
    signal,
  });
}

/** Recent sessions, newest first. */
export function getSessions(signal?: AbortSignal): Promise<SessionSummary[]> {
  return request<SessionSummary[]>("/api/sessions", { signal });
}

export function getSession(id: number, signal?: AbortSignal): Promise<SessionDetail> {
  return request<SessionDetail>(`/api/sessions/${id}`, { signal });
}

/**
 * Fetch MP3 audio for a line of Pip's speech as an object URL.
 * The caller is responsible for revoking the URL when done.
 */
export async function fetchTtsUrl(
  text: string,
  scenarioId?: string,
  signal?: AbortSignal,
): Promise<string> {
  // Apply the user's voice overrides (null = follow the scenario voice).
  const v = useVoice.getState();
  const body: Record<string, unknown> = { text, scenario_id: scenarioId };
  if (v.vcn) body.vcn = v.vcn;
  if (v.speed != null) body.speed = v.speed;
  if (v.pitch != null) body.pitch = v.pitch;
  const res = await fetch(`${BASE_URL}/api/tts`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
    signal: withTimeout(signal, 30_000),
  });
  if (!res.ok) throw new Error(`tts failed: ${res.status}`);
  return URL.createObjectURL(await res.blob());
}

/** Transcribe 16 kHz mono PCM via the backend (iFlytek ASR). */
export async function postAsr(pcm: ArrayBuffer, signal?: AbortSignal): Promise<string> {
  const res = await fetch(`${BASE_URL}/api/asr`, {
    method: "POST",
    headers: { "Content-Type": "application/octet-stream" },
    body: pcm,
    signal: withTimeout(signal, 45_000),
  });
  if (!res.ok) throw new Error(`asr failed: ${res.status}`);
  const data = (await res.json()) as { text: string };
  return data.text;
}

export interface WordScore {
  word: string;
  score: number;
}

export interface PronunciationResult {
  overall: number;
  accuracy: number;
  fluency: number;
  integrity: number;
  standard: number;
  words: WordScore[];
}

/** Score how well the given 16 kHz PCM reads `text` (iFlytek ISE). */
export async function postPronunciation(
  text: string,
  pcm: ArrayBuffer,
  signal?: AbortSignal,
): Promise<PronunciationResult> {
  const res = await fetch(`${BASE_URL}/api/pronunciation?text=${encodeURIComponent(text)}`, {
    method: "POST",
    headers: { "Content-Type": "application/octet-stream" },
    body: pcm,
    signal: withTimeout(signal, 45_000),
  });
  if (!res.ok) throw new Error(`pronunciation failed: ${res.status}`);
  return (await res.json()) as PronunciationResult;
}

/** Suggest a few natural things the learner could say next. */
export async function postHint(
  scenarioId: string,
  messages: ChatMessage[],
  signal?: AbortSignal,
): Promise<string[]> {
  const res = await fetch(`${BASE_URL}/api/hint`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ scenario_id: scenarioId, messages }),
    signal: withTimeout(signal, 30_000),
  });
  if (!res.ok) throw new Error(`hint failed: ${res.status}`);
  const data = (await res.json()) as { suggestions: string[] };
  return data.suggestions;
}

export interface DailyLine {
  text: string;
  author: string;
  zh: string;
  usage?: string;
}

/** Ask DeepSeek for a fresh batch of short lines to shadow. */
export function getDailyLines(n = 5, signal?: AbortSignal): Promise<DailyLine[]> {
  return request<{ lines: DailyLine[] }>(`/api/daily-lines?n=${n}`, { signal }).then(
    (r) => r.lines,
  );
}

export interface InterviewResult {
  question: string;
  answer: string;
  score: number;
  level: string;
  feedback: string;
  sample_answer: string;
}

export interface InterviewScore {
  overall: number;
  results: InterviewResult[];
}

/** TOEFL-style independent speaking questions for the timed drill. */
export function getInterviewQuestions(n = 4, signal?: AbortSignal): Promise<string[]> {
  return request<{ questions: string[] }>(`/api/interview/questions?n=${n}`, { signal }).then(
    (r) => r.questions,
  );
}

/** Rate the spoken answers (ETS-style) and return feedback + sample answers. */
export function scoreInterview(
  items: { question: string; answer: string }[],
  signal?: AbortSignal,
): Promise<InterviewScore> {
  return request<InterviewScore>("/api/interview/score", {
    method: "POST",
    body: JSON.stringify({ items }),
    signal,
  });
}

export interface PracticeRecord {
  id: number;
  kind: string;
  score: number;
  title: string;
  created_at: string;
}

export interface Stats {
  streak_days: number;
  today_count: number;
  today_goal: number;
  level: number;
  xp: number;
  xp_to_next: number;
  total_sessions: number;
  total_practice: number;
  words_count: number;
}

/** Save one practice result (pronunciation score / timed-Q&A result). */
export function savePractice(
  kind: string,
  score: number,
  title = "",
  detail = "",
  signal?: AbortSignal,
): Promise<PracticeRecord> {
  return request<PracticeRecord>("/api/practice", {
    method: "POST",
    body: JSON.stringify({ kind, score, title, detail }),
    signal,
  });
}

export function getPractice(kind?: string, limit = 100, signal?: AbortSignal): Promise<PracticeRecord[]> {
  const q = new URLSearchParams({ limit: String(limit) });
  if (kind) q.set("kind", kind);
  return request<PracticeRecord[]>(`/api/practice?${q.toString()}`, { signal });
}

/** Real activity stats: streak, level/XP, today vs goal, totals. */
export function getStats(signal?: AbortSignal): Promise<Stats> {
  return request<Stats>("/api/stats", { signal });
}

export interface Word {
  id: number;
  text: string;
  meaning: string;
  example: string;
  scenario_id: string;
  kind: string; // "word" | "sentence"
  mastered: boolean;
  created_at: string;
  box?: number; // spaced-repetition Leitner box
  due_at?: string | null;
  last_reviewed?: string | null;
}

export function getWords(signal?: AbortSignal): Promise<Word[]> {
  return request<Word[]>("/api/words", { signal });
}

export function postWord(
  payload: {
    text: string;
    scenario_id?: string;
    meaning?: string;
    example?: string;
    kind?: string;
  },
  signal?: AbortSignal,
): Promise<Word> {
  return request<Word>("/api/words", {
    method: "POST",
    body: JSON.stringify(payload),
    signal,
  });
}

/** Words whose spaced-repetition review is due (not yet mastered). */
export function getDueWords(kind?: string, signal?: AbortSignal): Promise<Word[]> {
  const q = kind ? `?kind=${kind}` : "";
  return request<Word[]>(`/api/words/due${q}`, { signal });
}

/** Record an SRS review: remembered pushes the next review out, forgot resets it. */
export function reviewWord(id: number, remembered: boolean, signal?: AbortSignal): Promise<Word> {
  return request<Word>(`/api/words/${id}/review`, {
    method: "POST",
    body: JSON.stringify({ remembered }),
    signal,
  });
}

export function patchWord(id: number, mastered: boolean, signal?: AbortSignal): Promise<Word> {
  return request<Word>(`/api/words/${id}`, {
    method: "PATCH",
    body: JSON.stringify({ mastered }),
    signal,
  });
}

export async function deleteWord(id: number, signal?: AbortSignal): Promise<void> {
  const res = await fetch(`${BASE_URL}/api/words/${id}`, { method: "DELETE", signal });
  if (!res.ok) throw new Error(`delete word failed: ${res.status}`);
}
