import {
  Briefcase,
  ClipboardCheck,
  Coffee,
  Handshake,
  Headphones,
  Hotel,
  MapPin,
  Megaphone,
  MessageCircle,
  PartyPopper,
  Plane,
  Presentation,
  Scale,
  ShoppingBag,
  Stethoscope,
  UtensilsCrossed,
  Users,
  Video,
  type LucideIcon,
} from "lucide-react";
import type { ScenarioIcon } from "../data/scenarios";

export const scenarioIcons: Record<ScenarioIcon, LucideIcon> = {
  Briefcase,
  Coffee,
  Users,
  Plane,
  Stethoscope,
  PartyPopper,
  UtensilsCrossed,
  ShoppingBag,
  Hotel,
  MapPin,
  Presentation,
  Handshake,
  Headphones,
  MessageCircle,
  Scale,
  Video,
  ClipboardCheck,
  Megaphone,
};
